// Facebook API targeting languages
export const FACEBOOK_LANGUAGES = [
  { id: 6, name: 'English (US)' },
  { id: 7, name: 'English (UK)' },
  { id: 9, name: 'French (France)' },
  { id: 10, name: 'French (Canada)' },
  { id: 12, name: 'Spanish (Spain)' },
  { id: 16, name: 'Spanish (Mexico)' },
  { id: 18, name: 'German (Germany)' },
  { id: 19, name: 'Italian (Italy)' },
  { id: 20, name: 'Portuguese (Brazil)' },
  { id: 21, name: 'Portuguese (Portugal)' },
  { id: 22, name: 'Dutch (Netherlands)' },
  { id: 23, name: 'Dutch (Belgium)' },
  { id: 24, name: 'Swedish (Sweden)' },
  { id: 25, name: 'Norwegian (Norway)' },
  { id: 26, name: 'Danish (Denmark)' },
  { id: 27, name: 'Finnish (Finland)' },
  { id: 28, name: 'Polish (Poland)' },
  { id: 29, name: 'Czech (Czech Republic)' },
  { id: 30, name: 'Hungarian (Hungary)' },
  { id: 31, name: 'Greek (Greece)' },
  { id: 32, name: 'Turkish (Turkey)' },
  { id: 33, name: 'Russian (Russia)' },
  { id: 34, name: 'Ukrainian (Ukraine)' },
  { id: 35, name: 'Bulgarian (Bulgaria)' },
  { id: 36, name: 'Romanian (Romania)' },
  { id: 37, name: 'Croatian (Croatia)' },
  { id: 38, name: 'Slovak (Slovakia)' },
  { id: 39, name: 'Slovenian (Slovenia)' },
  { id: 40, name: 'Estonian (Estonia)' },
  { id: 41, name: 'Latvian (Latvia)' },
  { id: 42, name: 'Lithuanian (Lithuania)' },
  { id: 43, name: 'Japanese (Japan)' },
  { id: 44, name: 'Korean (South Korea)' },
  { id: 45, name: 'Chinese (Simplified, China)' },
  { id: 46, name: 'Chinese (Traditional, Taiwan)' },
  { id: 47, name: 'Chinese (Traditional, Hong Kong)' },
  { id: 48, name: 'Thai (Thailand)' },
  { id: 49, name: 'Vietnamese (Vietnam)' },
  { id: 50, name: 'Indonesian (Indonesia)' },
  { id: 51, name: 'Malay (Malaysia)' },
  { id: 52, name: 'Filipino (Philippines)' },
  { id: 53, name: 'Hindi (India)' },
  { id: 54, name: 'Bengali (Bangladesh)' },
  { id: 55, name: 'Urdu (Pakistan)' },
  { id: 56, name: 'Arabic (Saudi Arabia)' },
  { id: 57, name: 'Arabic (Egypt)' },
  { id: 58, name: 'Arabic (United Arab Emirates)' },
  { id: 59, name: 'Hebrew (Israel)' },
  { id: 60, name: 'Persian (Iran)' }
]
